apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-config
data:
  guestbook-name: {{ .Values.config.guestbook_name }}
  backend-uri: {{ with .Values.config -}}
  {{- list "http://" $.Release.Name "." .backend_uri | join "" |  quote }}
{{- end }}
